# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-18 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recepie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recepies',
            field=models.ManyToManyField(related_name='ingredients', to='myapp.Recepie'),
        ),
    ]
