# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-19 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepie',
            new_name='Recipe',
        ),
    ]
